name: Preflight Checks

on:
  pull_request:

jobs:
  preflight_checks:
    name: "pre-commit hooks"
    runs-on: ubuntu-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.12"
          activate-environment: "true"
          enable-cache: "true"
          cache-dependency-glob: "uv.lock"

      - name: Sync uv virtual environment
        run: |
          uv sync --frozen --extra devel

      - name: Run pre-commit hooks
        run: |
          prek run --show-diff-on-failure --color=always --from-ref origin/${{ github.event.pull_request.base.ref }} --to-ref HEAD
